


function functionName(userInput) {
    //create array for values generated by input loop to be pushed into
    let array = [];
    //create for loop of input
    for (let i = 0; i <= userInput; i++) {
    //generate array of numbers up to and including user input
    let j = i.toString()
      if (j.includes('3')) {
      array.push("Won't you be my neighbor?");
    } else if (j.includes('2')) {
      array.push("Boop!");
    } else if (j.includes('1')) {
      array.push("Beep!");
    } else {
    array.push(j);
    };
  }
  
  alert(array);
  return(array);
}

  //collect number entered by user then alert to test functionality



  $(document).ready(function() {
    $("form#form").submit(function(event) {
      event.preventDefault();
      let userInput = $("input#submission").val();
      functionName(userInput);
    });
  });